\documentclass[xcolor=pdftex,dvipsnames,table]{beamer}
\usepackage[ngerman]{babel}
\usepackage[latin1]{inputenc}
\usepackage{amsmath,amsfonts,amssymb}
%\usepackage{colortbl}

\definecolor{lightgray}{gray}{0.9}


\definecolor{UniBlue}{RGB}{128,161,201}
\definecolor{UniDarkBlue}{RGB}{0,60,118}
\definecolor{UniRed}{RGB}{193,0,43}

\title{Non-inferiority Global Rank Test} %slide 1
\author{Irene Schmidtmann}
\date{March 25th, 2017}

\title{Non-inferiority Global Rank Test} %slide 1
\author{Irene Schmidtmann}
\date{March 25th, 2017}
\begin{document}
\maketitle
\begin{frame} %slide 2
\frametitle{Purpose}
Determining $E(U)$ and $var(U)$ according to the formula from Matsouaka and Betensky
\end{frame}
\SweaveOpts{concordance=TRUE}



\end{document}